## Course: Visual Analytics for Policy and Management

### Prof. José Manuel Magallanes, PhD 

```{r}
link='https://github.com/marcevl/Team-Assignments/raw/master/Internet2.RData'
load(file=url(link))
library(ggplot2)
str(Internet2)
```

```{r Heatmap, eval=TRUE}
library(ggplot2)

df.heatmap <- expand.grid(ISP = c("CenturyLink", "Wave", "GorgeNet"),
                          Satisfaction.Speed = c("1", "2", "3", "4", "5"))

df.heatmap$Download.Speed <- rnorm(nrow(df.heatmap))

ggplot(data = df.heatmap, aes(x = Satisfaction.Speed, y = ISP)) +
  geom_tile(aes(fill = Download.Speed))
```

```{r Regression, eval=TRUE}
library(dotwhisker)
library(broom)
library(dplyr)

model1=lm(Satisfaction.Speed~Upload.Speed+Download.Speed,data=Internet2[,-1])
summary(model1)

model1_t = tidy(model1) %>% mutate(model = "Model 1") %>%
   relabel_predictors(Upload.Speed = "Upload",
                     Download.Speed = "Download",
                     Subscribed.Speed = "Subscribed")
```

```{r}
model2=lm(Satisfaction.Speed~Download.Speed+Upload.Speed+Subscribed.Speed,data=Internet2[,-1]) # ~. means: all the remaining variables
summary(model2)

model2_t <- tidy(model2) %>% mutate(model = "Model 2") %>%
   relabel_predictors(Upload.Speed = "Upload",
                     Download.Speed = "Download",
                     Subscribed.Speed = "Subscribed")
```

```{r}
# combining
allModels=rbind(model1_t, model2_t)

#plotting
dwplot(allModels) 
```

```{r}
dwplot(allModels) + 
  geom_vline(xintercept = 0, 
               colour = "green", 
               linetype = 2) + 
  scale_colour_grey(start = .1, end = .7) + 
  labs(y = "Independent Variables",
title = "Correlation Between Speed Satisfaction & 
Download, Upload, and Subscribed Speed", 
         caption = "Source:Stevenson Business and Organization Internet Survey") +
  theme(plot.margin=unit(c(1,1,.5,.5),'cm'),
                    plot.title=(element_text(face='bold',
                                            size=15,
                                            hjust=0.5)),
                    plot.subtitle = (element_text(hjust = 0.5, vjust = 2)),
                    plot.caption=element_text(size=9, vjust=-2),
                    text=element_text(color='black', size = 11),
                    legend.title = element_blank(),
                    axis.line.y=element_line(color = 'black'),
                    axis.line.x=element_line(color='black'),
                    axis.text=element_text(size=8))
```

```{r}
##Nathan's Heatmap!

#loading data
link='https://github.com/marcevl/Team-Assignments/raw/master/Internet2.RData'
load(file=url(link))

#changing download speed to a variable from 0-1
Internet2$Download.Speed.Rescaled <- rescale(Internet2$Download.Speed)

#adding data to data frame
df1 <- Internet2

#removing obervation with outlier
df1 <- df1[-3,]

#removing unnecessary variables from heatmap data frame
df.heatmap <- df1[c(2,6,10,40)]

#removing ISPs without many observations
df.heatmap <- subset(df.heatmap, ISP %in% c("Wave", "CenturyLink", "GorgeNet"))

#plotting heat map
ggplot(data = df.heatmap, aes(x = Satisfaction.Speed, y = ISP)) +
  geom_tile(aes(fill = Download.Speed.Rescaled))
```






